#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";

function usage() {
  console.log("Usage: node export_pdf.mjs --input-html <file.html> --output-pdf <file.pdf> [--engine-cmd <cmd with {input} {output}>]");
}

function parseArgs(argv) {
  const out = { inputHtml: "", outputPdf: "", engineCmd: "" };
  for (let i = 2; i < argv.length; i++) {
    const k = argv[i];
    const v = argv[i + 1];
    if (k === "--input-html") out.inputHtml = v, i++;
    else if (k === "--output-pdf") out.outputPdf = v, i++;
    else if (k === "--engine-cmd") out.engineCmd = v, i++;
    else if (k === "--help" || k === "-h") return null;
    else throw new Error(`Unknown arg: ${k}`);
  }
  if (!out.inputHtml || !out.outputPdf) throw new Error("--input-html and --output-pdf are required");
  return out;
}

function q(s) {
  return `\"${String(s).replaceAll("\\", "/")}\"`;
}

function runShell(cmd) {
  return spawnSync("cmd.exe", ["/d", "/s", "/c", cmd], { stdio: "pipe", encoding: "utf8" });
}

function existsPdf(file) {
  return fs.existsSync(file) && fs.statSync(file).size > 1000;
}

function main() {
  const args = parseArgs(process.argv);
  if (!args) return usage();

  const input = path.resolve(args.inputHtml);
  const output = path.resolve(args.outputPdf);
  if (!fs.existsSync(input)) throw new Error(`Input html not found: ${input}`);
  fs.mkdirSync(path.dirname(output), { recursive: true });

  const inputUrl = `file:///${input.replaceAll("\\", "/")}`;

  const tried = [];
  const candidates = [];

  if (args.engineCmd) {
    const cmd = args.engineCmd
      .replaceAll("{input}", input.replaceAll("\\", "/"))
      .replaceAll("{output}", output.replaceAll("\\", "/"))
      .replaceAll("{input_url}", inputUrl);
    candidates.push({ name: "custom", cmd });
  }

  const edge = "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe";
  const chrome = "C:/Program Files/Google/Chrome/Application/chrome.exe";
  const chromeX86 = "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe";
  for (const p of [edge, chrome, chromeX86]) {
    if (!fs.existsSync(p)) continue;
    const cmd = `${q(p)} --headless --disable-gpu --print-to-pdf=${q(output)} ${q(inputUrl)}`;
    candidates.push({ name: path.basename(p), cmd });
  }

  for (const c of candidates) {
    tried.push(c.name);
    const r = runShell(c.cmd);
    if (r.status === 0 && existsPdf(output)) {
      console.log(`PDF generated by ${c.name}: ${output}`);
      return;
    }
  }

  throw new Error(`Failed to generate pdf. Tried engines: ${tried.join(", ") || "none"}`);
}

try {
  main();
} catch (err) {
  console.error(`Error: ${err.message}`);
  process.exit(1);
}

